/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_kayshen_voicechanger_VoiceUtil */

#ifndef _Included_cn_kayshen_voicechanger_VoiceUtil
#define _Included_cn_kayshen_voicechanger_VoiceUtil
#ifdef __cplusplus
extern "C" {
#endif
#undef cn_kayshen_voicechanger_VoiceUtil_MODE_NORMAL
#define cn_kayshen_voicechanger_VoiceUtil_MODE_NORMAL 0L
#undef cn_kayshen_voicechanger_VoiceUtil_MODE_LORIE
#define cn_kayshen_voicechanger_VoiceUtil_MODE_LORIE 1L
#undef cn_kayshen_voicechanger_VoiceUtil_MODE_TERROR
#define cn_kayshen_voicechanger_VoiceUtil_MODE_TERROR 2L
#undef cn_kayshen_voicechanger_VoiceUtil_MODE_UNCLE
#define cn_kayshen_voicechanger_VoiceUtil_MODE_UNCLE 3L
#undef cn_kayshen_voicechanger_VoiceUtil_MODE_FUNNY
#define cn_kayshen_voicechanger_VoiceUtil_MODE_FUNNY 4L
#undef cn_kayshen_voicechanger_VoiceUtil_MODE_VACANT
#define cn_kayshen_voicechanger_VoiceUtil_MODE_VACANT 5L
/*
 * Class:     cn_kayshen_voicechanger_VoiceUtil
 * Method:    fix
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_cn_kayshen_voicechanger_VoiceUtil_fix
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
